use_frameworks!

platform :ios, '15.0'

target 'CustomActivityRingiOS_Example' do
  pod 'CustomActivityRingiOS', :path => '../'

  target 'CustomActivityRingiOS_Tests' do
    inherit! :search_paths

    
  end
end
